
bf_scene = {

'name' : 'root',

'0a' : {   # object

    'name' : 'object',
    '0a' : 'name',
    '12' : 'identifier',
    '1a' : {   # component
        'name' : 'component',
        '0a' : 'component_type',
        '10' : 'number',
        '1a' : 'name',
        '20' : '?linked_component',
        '322' : {   # sprite
            'name' : 'sprite',
        },
        '32a' : {   # model
            'name' : '3D_model',
            '0a' : 'name',
            '15' : 'u0',
            '1d' : 'u1',
            '25' : 'u2',
            '2a' : {
                'name' : 'u3',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '32' : {
                'name' : 'u4',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '38' : 'u5',
            '42' : {
                'name' : 'u6',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
        },
        '332' : {   # keyframe animation
            'name' : 'keyframe_animation',
            '08' : 'linked_model_component_number',
            '12' : 'name',
            '18' : 'u0',
            '25' : 'u1',
            '28' : 'u2',
        },
        '33a' : {   # blend animation
            'name' : 'blend_animation',
            '08' : 'animation_1',
            '10' : 'animation_2',
            '1d' : 'u0',
            '25' : 'u1',
        },
        '342' : {   # model transform controller
            'name' : 'model_transform_controller',
            '08' : 'u0',
            '1a' : {
                'name' : 'u1',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '2d' : 'u2',
        },
        '372' : {   # ground polygon
            'name' : 'ground_polygon',
            '12' : {
                'name' : 'vertex_list',
                '0a' : {
                    'name' : 'vertex_pos',
                    '0d' : 'x_pos',
                    '15' : 'y_pos',
                },
                '10' : 'u1',
                '18' : 'u2',
            },
            '18' : 'u1',
            '25' : 'u2',
            '2d' : 'u3',
            '32' : 'u4',
            '3d' : 'u5',
            '40' : 'u6',
        },
        '37a' : {   # ground mesh
            'name' : 'ground_mesh',
            '3a' : {
                'name' : 'u0',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '42' : {
                'name' : 'u1',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '22' : {
                    'name' : 'u3',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '2a' : {
                    'name' : 'u4',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '32' : {
                    'name' : 'u5',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '52' : {
                    'name' : 'u6',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '25' : 'u3',
                    '2a' : {
                        'name' : 'u4',
                        '0a' : 'name',
                        '10' : 'u0',
                        '20' : 'u2',
                    },
                },
                '5a' : {
                    'name' : 'u7',
                    '0d' : 'u',
                    '15' : 'v',
                    '1d' : 'w',
                    '25' : 'x',
                    '2d' : 'y',
                    '35' : 'z',
                },
                '192' : [2, 'u8'],
                '19a' : [2, 'u9'],
            },
            '4a' : {
                'name' : 'u2',
                '08' : 'u0',
                '10' : 'u1',
                '22' : {
                    'name' : 'u2',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '2a' : {
                    'name' : 'u3',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '32' : {
                    'name' : 'u4',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '52' : {
                    'name' : 'u5',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '25' : 'u3',
                    '2a' : {
                        'name' : 'u4',
                        '0a' : 'u0',
                        '10' : 'u1',
                        '20' : 'u2',
                    },
                },
                '5a' : {
                    'name' : 'u6',
                    '0d' : 'u',
                    '15' : 'v',
                    '1d' : 'w',
                    '25' : 'x',
                    '2d' : 'y',
                    '35' : 'z',
                },
                '192' : [2, 'u7'],
            },
            '52' : {
                'name' : 'u3',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '58' : 'u4',
        },
        '382' : {   # ground mesh generator
            'name' : 'ground_mesh_generator',
            '08' : 'ground_polygon',
            '10' : 'ground_mesh',
            '18' : 'texture_mapping_1',
            '20' : 'texture_mapping_2',
            '28' : 'u4',
            '35' : 'u5',
            '38' : 'u6',
            '45' : 'u7',
            '4d' : 'u8',
            '55' : 'u9',
            '5d' : 'u10',
            '73f2' : 'u11',
        },
        '38a' : {   # texture mapping
            'name' : 'texture_mapping',
            '0a' : 'texture_file',
            '15' : 'u0',
            '1a' : {
                'name' : 'u1',
                '0d' : 'u1',
                '15' : 'u2',
            },
        },
        '392' : {   # water mesh
            'name' : 'water_mesh',
            '08' : 'u0',
            '10' : 'u1',
            '1a' : {
                'name' : 'u2',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '22' : {
                'name' : 'u3',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },

        },
        '3c2' : {   # collision shape
            'name' : 'collision_shape',
            '0a' : {
                'name' : 'u0',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '12' : {
                'name' : 'u1',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'y',
                    '15' : 'z',
                },
                '15' : 'u1',
            },
            '1a' : {
                'name' : 'u2',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'y',
                    '15' : 'z',
                },
                '10' : 'u3',
                '18' : 'u4',
            },
        },
        '3ca' : {   # collision shape 2
            'name' : 'collision_shape_2',
            '10' : 'u0',
            '18' : 'u1',
            '20' : 'u2',
            '28' : 'u3',
            '35' : 'w',
            '3d' : 'x',
            '40' : 'interaction_type',
            '4a' : {
                'name' : 'lua_chunk_0',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '52' : {
                'name' : 'lua_chunk_1',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '58' : 'z',
            '62' : {
                'name' : 'lua_chunk_2',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '6d' : 'u4',
            '70' : 'u5',
        },
        '3d2' : {   # damage
            'name' : 'damage',
            '08' : 'u0',
            '10' : 'u1',
            '18' : 'u2',
            '20' : 'u3',
            '28' : 'u4',
            '35' : 'u5',
            '3d' : 'u6',
            '40' : 'u7',
            '48' : 'u8',
        },
        '3da' : {   # health
            'name' : 'health',
            '08' : 'u0',
            '10' : 'u1',
            '1a' : {
                'name' : 'u2',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            }
        },
        '3e2' : {   # bone controlled collision shape
            'name' : 'bone_controlled_collision_shape',
            '08' : 'model_component',
            '12' : 'bone_name',
        },
        '3ea' : {   # object link controller
            'name' : 'object_link_controller',
            '0a' : 'u0',
            '12' : 'u1',
            '1a' : {
                'name' : 'u2',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '22' : {
                'name' : 'u3',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '2a' : {
                'name' : 'u4',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
        },     
        '412' : {   # light
            'name' : 'light',
            '08' : 'u0',
            '15' : 'u1',
            '1a' : {
                'name' : 'u2',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '25' : 'u3',
            '2d' : 'u4',
            '32' : {
                'name' : 'u5',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '3d' : 'u6',
        },
        '462' : {   # sound effect
            'name' : 'sound_effect',
            '0a' : 'sound',
            '15' : 'u0',
            '1d' : 'u1',
        },
        '4aa' : {   # animation controller
            'name' : 'animation_controller',
            '08' : 'model_component',
            '10' : 'u1',
            '18' : 'u2',
        },
        '4c2' : {   # entity
            'name' : 'entity',
            '08' : 'u0',
            '10' : 'u1',
        },
        '4ca' : {   # bush controller
            'name' : 'bush_controller',
            '08' : 'touched_animation',
            '10' : 'u0',
            '18' : 'u1',
        },
        '4d2' : {   # elevator controller
            'name' : 'elevator_controller',
            '08' : 'utility_shape_component',
            '10' : 'u0',
        },
        '4da' : {   # pressure trigger
            'name' : 'pressure_trigger',
            '0d' : 'u0',
            '12' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secrndary_chunk'],
            },
            '1a' : 'u1',
            '20' : 'u2',
        },
        '4f2' : {   # ?monster entity
            'name' : '?monster_entity',
            '0a' : 'u0',
            '12' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '18' : 'u2',
            '20' : 'u3',
        },
        '4fa' : {   # physics object
            'name' : 'physics_object',
            '08' : 'u0',
            '1d' : 'u1',
            '25' : 'u2',
            '2d' : 'u3',
            '35' : 'u4',
            '38' : 'u5',
            '45' : 'u6',
        },
        '4e2' : {   # door controller
            'name' : 'door_controller',
            '08' : 'u0',
            '10' : 'u1',
            '20' : 'u2',
            '28' : 'u3',
            '30' : 'u4',
        },
        '4ea' : {   # program
            'name' : 'program',
            '08' : 'u0',
            '12' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '18' : 'u1',
            '20' : 'u2',
        },
        '502' : {   # breakable object
            'name' : 'breakable_object',
            '08' : 'u0',
            '10' : 'u1',
            '18' : 'u2',
            '22' : 'u3',
        },
        '50a' : {   # entity controller
            'name' : 'entity_controller',
            '08' : 'entity_component',
            '10' : 'animation_controller_component',
            '18' : 'u2',
            '20' : 'collision_shape',
            '2d' : 'u4',
            '35' : 'u5',
            '3d' : 'u6',            
            '40' : 'u7',
        },
        '512' : {   # entity action
            'name' : 'entity_action',
            '0a' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            }
        },
        '51a' : {   # physics platform
            'name' : 'physics_platform',
            '0d' : 'w',
            '15' : 'x',
            '1d' : 'y',
            '25' : 'z',
        },
        '522' : {   # entity info
            'name' : 'entity_info',
            '0a' : 'name',
        },
        '52a' : {   # hero entity
            'name' : 'hero_entity',
            '0a' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            }
        },
        '642' : {   # file
            'name' : 'file',
            '0a' : 'filename',
        },
        '692' : {   # properties
            'name' : 'properties',
            '0a' : 'u0',
        },
        '7d2' : {   # particle emitter
            'name' : 'particle_emitter',
            '10' : 'particle',
            '18' : 'u1',
            '20' : 'u2',
            '28' : 'u3',
            '30' : 'u4',
            '3a' : {
                'name' : 'u5',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '1d' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '35' : 'u5',
                '3a' : {
                    'name' : 'u6',
                    '0d' : 'u0',
                    '15' : 'u1',
                    '1d' : 'u2',
                }
            },
            '40' : 'u6',
            '4a' : {
                'name' : 'u7',
                '0d' : 'u0',
                '15' : 'u1',
                '1d' : 'u2',
            },
            '52' : {
                'name' : 'u8',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
        },
        '7da' : {   # particle
            'name' : 'particle',
            '0a' : 'name',
            '15' : 'u0',
        },
        '7ea' : {   # fire emitter
            'name' : 'fire_emitter',
            '08' : 'particle_emitter',
            '18' : 'light',
            '2a' : {
                'name' : 'u0',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '35' : 'u1',
            '3d' : 'u2',
            '42' : {
                'name' : 'u3',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '4a' : {
                'name' : 'u4',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
        },
        '7f2' : {   # simple glow
            'name' : 'simple_glow',
            '0a' : {
                'name' : 'u0',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '15' : 'u1',
            '18' : 'u2',
            '25' : 'u3',
            '2d' : 'u4',
            '35' : 'u5',
            '3a' : {
                'name' : 'u6',
                '0d' : 'y',
                '15' : 'z',
            },
        },
        '802' : {   # orbit controller
            'name' : 'orbit_controller',
            '0a' : {
                'name' : 'u0',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '15' : 'speed',
            '1d' : 'radius',
        },
        '972' : {   # monster controller
            'name' : 'monster_controller',
            '0d' : 'u0',
            '10' : 'u1',
            '18' : 'u2',
            '20' : 'u3',
        },
        '982' : {   # charging monster controller
            'name' : 'charging_monster_controller',
            '08' : 'walk_animation',
            '10' : 'charge_animation',
            '18' : 'run_animation',
            '25' : 'u0',
            '2d' : 'u1',
        },
        '98a' : {    #t
            'name' : 'temp1',
            '08' : 'u0',
            '10' : 'u2',
            '18' : 'u3',
            '20' : 'u4',
            '28' : 'u5',
        },
        '992' : {   # attack
            'name' : 'attack',
            '08' : 'keyframe_animation_component',
            '10' : 'u0',
            '18' : 'u1',
            '20' : 'u2',
            '2d' : 'u3',
            '35' : 'u4',
            '3d' : 'u5',
            '45' : 'u6',
            '4d' : 'u7',
            '55' : 'u8',
            '5a' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '65' : 'u9',
            '6d' : 'u10',
        },
        '9aa' : {   # static monster controller
            'name' : 'static_monster_controller',
            '08' : 'u0',
        },
        '9c2' : {   # bouncing monster controller
            'name' : 'bouncing_monster_controller',
            '08' : 'jump_animation',
            '10' : 'land_animation',
            '1d' : 'u0',
            '25' : 'u1',
        },
        '9d2' : {   # generic monster controller
            'name' : 'generic_monster_controller',
            '08' : 'walk_animation',
        },
        'c82' : {   # swingable weapon
            'name' : 'swingable_weapon',
            '08' : 'linked_model_component_number',
            '10' : 'u1',
            '20' : 'u2',
            '28' : 'u3',
            '30' : 'u4',
            '38' : 'u5',
            '40' : 'u6',
            '48' : 'u7',
            '55' : 'w',
            '5d' : 'x',
            '65' : 'y',
            '6d' : 'z',
            '72' : 'u8',
        },
        'c8a' : {   # swingable weapon controller
            'name' : 'swingable_weapon_controller',
            '08' : 'parent_model',
            '12' : 'bone',
            '1a' : 'child_model'
        },
        'c9a' : {   # weapon glow
            'name' : 'weapon_glow',
            '08' : 'u0',
            '12' : {
                'name' : 'u1',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '1a' : {
                'name' : 'u2',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '25' : 'u3',
        },
        'ca2' : {   # weapon trail
            'name' : 'weapon_trail',
            '0a' : {
                'name' : 'u0',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            }
        },
        'fa2' : {   # portal
            'name' : 'portal',
            '0a' : 'target_level',
            '12' : 'spawnpoint',
            '18' : 'touchable',
            '20' : 'collision_shape_component',
        },
        'faa' : {   # spawnpoint
            'name' : 'spawnpoint',
            '08' : 'u0',
            '12' : {
                'name' : 'u1',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            }
        },
        'fb2' : {   # collectable item
            'name' : 'collectable_item',
            '08' : 'u0',
            '10' : 'u1',
            '1a' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '22' : 'name',
            '2a' : '?model',
            '30' : 'u0',
        },
        'fca' : {   # item drop
            'name' : 'item_drop',
            '0a' : 'name',
            '12' : 'identifier',
            '1a' : {   # item
                'name' : 'item',
                '0a' : 'item_type',
                '12' : 'identifier',
                '1d' : 'u0',
                '20' : 'u1',
                '28' : 'u2',
            },
            '20' : 'u0',
            '28' : 'u1',
        },
        '1132' : {   # magic bolt
            'name' : 'magic_bolt',
            '08' : 'u0',
            '10' : 'u1',
            '18' : 'u2',
            '22' : {
                'name' : 'u3',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '2d' : 'u4',
        },
        '113a' : {   # magic explosion
            'name' : 'magic_explosion',
            '08' : 'u0',
            '10' : 'u1',
            '1a' : {
                'name' : 'u2',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '25' : 'u3',
            '2d' : 'u4',
        },
        '1142' : {   # skill
            'name' : 'skill',
            '08' : 'u0',
            '12' : {
                'name' : 'u1',
                '0d' : 'x',
                '15' : 'y',
                '1d' : 'z',
            },
            '1a' : 'cast_animation',

        },
        '114a' : {   # magic spell cast
            'name' : 'magic_spell_cast',
            '08' : 'particle_emitter',
            '10' : 'u0',
        },
        '115a' : {   # projectile controller
            'name' : 'projectile_controller',
            '08' : 'u0',
            '10' : 'u1',
        },
        '1172' : { #t
            'name' : 'temp0',
        },
    },
    '22' : {
        'name' : 'position',
        '0d' : 'x_position',
        '15' : 'y_position',
    },
    '2d' : 'z_position',
    '35' : 'rotation',
    '3d' : 'scale',
    '42' : {
        'name' : 'u2',
        '0d' : 'w',
        '15' : 'x',
        '1d' : 'y',
        '25' : 'z',
    },
    '48' : 'hidden',
    '52' : {
        'name' : 'lua_chunk',
        '0a' : [1,'main_chunk'],
        '12' : [2, 'secondary_chunk'],
    },
},


'12' : {
    'name' : '?scene_info',
    '0a' : 'name',
    '12' : {
        'name' : 'u0',
        '0a' : {
            'name' : 'u0',
            '12' : 'name',
            '1a' : {   # component
                'name' : 'component',
                '0a' : 'component_type',
                '10' : 'number',
                '1a' : 'name',
                '20' : '?linked_component',
                '322' : {   # sprite
                    'name' : 'sprite',
                },
                '32a' : {   # model
                    'name' : '3D_model',
                    '0a' : 'name',
                    '15' : 'u0',
                    '1d' : 'u1',
                    '25' : 'u2',
                    '2a' : {
                        'name' : 'u3',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '32' : {
                        'name' : 'u4',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '38' : 'u5',
                    '42' : {
                        'name' : 'u6',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                },
                '332' : {   # keyframe animation
                    'name' : 'keyframe_animation',
                    '08' : 'linked_model_component_number',
                    '12' : 'name',
                    '18' : 'u0',
                    '25' : 'u1',
                    '28' : 'u2',
                },
                '33a' : {   # blend animation
                    'name' : 'blend_animation',
                    '08' : 'animation_1',
                    '10' : 'animation_2',
                    '1d' : 'u0',
                    '25' : 'u1',
                },
                '342' : {   # model transform controller
                    'name' : 'model_transform_controller',
                    '08' : 'u0',
                    '1a' : {
                        'name' : 'u1',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '2d' : 'u2',
                },
                '372' : {   # ground polygon
                    'name' : 'ground_polygon',
                    '12' : {
                        'name' : 'vertex_list',
                        '0a' : {
                            'name' : 'vertex_pos',
                            '0d' : 'x_pos',
                            '15' : 'y_pos',
                        },
                        '10' : 'u1',
                        '18' : 'u2',
                    },
                    '18' : 'u1',
                    '25' : 'u2',
                    '2d' : 'u3',
                    '32' : 'u4',
                    '3d' : 'u5',
                    '40' : 'u6',
                },
                '37a' : {   # ground mesh
                    'name' : 'ground_mesh',
                    '3a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '42' : {
                        'name' : 'u1',
                        '08' : 'u0',
                        '10' : 'u1',
                        '1a' : {
                            'name' : 'u2',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '22' : {
                            'name' : 'u3',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '2a' : {
                            'name' : 'u4',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '32' : {
                            'name' : 'u5',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '52' : {
                            'name' : 'u6',
                            '0a' : {
                                'name' : 'u0',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '12' : {
                                'name' : 'u1',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '1a' : {
                                'name' : 'u2',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '25' : 'u3',
                            '2a' : {
                                'name' : 'u4',
                                '0a' : 'name',
                                '10' : 'u0',
                                '20' : 'u2',
                            },
                        },
                        '5a' : {
                            'name' : 'u7',
                            '0d' : 'u',
                            '15' : 'v',
                            '1d' : 'w',
                            '25' : 'x',
                            '2d' : 'y',
                            '35' : 'z',
                        },
                        '192' : [2, 'u8'],
                        '19a' : [2, 'u9'],
                    },
                    '4a' : {
                        'name' : 'u2',
                        '08' : 'u0',
                        '10' : 'u1',
                        '22' : {
                            'name' : 'u2',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '2a' : {
                            'name' : 'u3',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '32' : {
                            'name' : 'u4',
                            '08' : 'u0',
                            '10' : 'u1',
                            '18' : 'u2',
                            '20' : 'u3',
                        },
                        '52' : {
                            'name' : 'u5',
                            '0a' : {
                                'name' : 'u0',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '12' : {
                                'name' : 'u1',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '1a' : {
                                'name' : 'u2',
                                '0d' : 'w',
                                '15' : 'x',
                                '1d' : 'y',
                                '25' : 'z',
                            },
                            '25' : 'u3',
                            '2a' : {
                                'name' : 'u4',
                                '0a' : 'u0',
                                '10' : 'u1',
                                '20' : 'u2',
                            },
                        },
                        '5a' : {
                            'name' : 'u6',
                            '0d' : 'u',
                            '15' : 'v',
                            '1d' : 'w',
                            '25' : 'x',
                            '2d' : 'y',
                            '35' : 'z',
                        },
                        '192' : [2, 'u7'],
                    },
                    '52' : {
                        'name' : 'u3',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '58' : 'u4',
                },
                '382' : {   # ground mesh generator
                    'name' : 'ground_mesh_generator',
                    '08' : 'ground_polygon',
                    '10' : 'ground_mesh',
                    '18' : 'texture_mapping_1',
                    '20' : 'texture_mapping_2',
                    '28' : 'u4',
                    '35' : 'u5',
                    '38' : 'u6',
                    '45' : 'u7',
                    '4d' : 'u8',
                    '55' : 'u9',
                    '5d' : 'u10',
                    '73f2' : 'u11',
                },
                '38a' : {   # texture mapping
                    'name' : 'texture_mapping',
                    '0a' : 'texture_file',
                    '15' : 'u0',
                    '1a' : {
                        'name' : 'u1',
                        '0d' : 'u1',
                        '15' : 'u2',
                    },
                },
                '392' : {   # water mesh
                    'name' : 'water_mesh',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '22' : {
                        'name' : 'u3',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },

                },
                '3c2' : {   # collision shape
                    'name' : 'collision_shape',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '12' : {
                        'name' : 'u1',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'y',
                            '15' : 'z',
                        },
                        '15' : 'u1',
                    },
                    '1a' : {
                        'name' : 'u2',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'y',
                            '15' : 'z',
                        },
                        '10' : 'u3',
                        '18' : 'u4',
                    },
                },
                '3ca' : {   # collision shape 2
                    'name' : 'collision_shape_2',
                    '10' : 'u0',
                    '18' : 'u1',
                    '20' : 'u2',
                    '28' : 'u3',
                    '35' : 'w',
                    '3d' : 'x',
                    '40' : 'interaction_type',
                    '4a' : {
                        'name' : 'lua_chunk_0',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '52' : {
                        'name' : 'lua_chunk_1',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '58' : 'z',
                    '62' : {
                        'name' : 'lua_chunk_2',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '6d' : 'u4',
                    '70' : 'u5',
                },
                '3d2' : {   # damage
                    'name' : 'damage',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                    '28' : 'u4',
                    '35' : 'u5',
                    '3d' : 'u6',
                    '40' : 'u7',
                    '48' : 'u8',
                },
                '3da' : {   # health
                    'name' : 'health',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    }
                },
                '3e2' : {   # bone controlled collision shape
                    'name' : 'bone_controlled_collision_shape',
                    '08' : 'u0',
                    '12' : 'bone_name',
                },
                '3ea' : {   # object link controller
                    'name' : 'object_link_controller',
                    '0a' : 'u0',
                    '12' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '22' : {
                        'name' : 'u3',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '2a' : {
                        'name' : 'u4',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                },     
                '412' : {   # light
                    'name' : 'light',
                    '08' : 'u0',
                    '15' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '25' : 'u3',
                    '2d' : 'u4',
                    '32' : {
                        'name' : 'u5',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '3d' : 'u6',
                },
                '462' : {   # sound effect
                    'name' : 'sound_effect',
                    '0a' : 'sound',
                    '15' : 'u0',
                    '1d' : 'u1',
                },
                '4aa' : {   # animation controller
                    'name' : 'animation_controller',
                    '08' : 'model_component',
                    '10' : 'u1',
                    '18' : 'u2',
                },
                '4c2' : {   # entity
                    'name' : 'entity',
                    '08' : 'u0',
                    '10' : 'u1',
                },
                '4ca' : {   # bush controller
                    'name' : 'bush_controller',
                    '08' : 'touched_animation',
                    '10' : 'u0',
                    '18' : 'u1',
                },
                '4d2' : {   # elevator controller
                    'name' : 'elevator_controller',
                    '08' : 'utility_shape_component',
                    '10' : 'u0',
                },
                '4da' : {   # pressure trigger
                    'name' : 'pressure_trigger',
                    '0d' : 'u0',
                    '12' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secrndary_chunk'],
                    },
                    '1a' : 'u1',
                    '20' : 'u2',
                },
                '4f2' : {   # ?monster entity
                    'name' : '?monster_entity',
                    '0a' : 'u0',
                    '12' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '4fa' : {   # physics object
                    'name' : 'physics_object',
                    '08' : 'u0',
                    '1d' : 'u1',
                    '25' : 'u2',
                    '2d' : 'u3',
                    '35' : 'u4',
                    '38' : 'u5',
                    '45' : 'u6',
                },
                '4e2' : {   # door controller
                    'name' : 'door_controller',
                    '08' : 'u0',
                    '10' : 'u1',
                    '20' : 'u2',
                    '28' : 'u3',
                    '30' : 'u4',
                },
                '4ea' : {   # program
                    'name' : 'program',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '18' : 'u1',
                    '20' : 'u2',
                },
                '502' : {   # breakable object
                    'name' : 'breakable_object',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '22' : 'u3',
                },
                '50a' : {   # entity controller
                    'name' : 'entity_controller',
                    '08' : 'entity_component',
                    '10' : 'animation_controller_component',
                    '18' : 'u2',
                    '20' : 'collision_shape',
                    '2d' : 'u4',
                    '35' : 'u5',
                    '3d' : 'u6',            
                    '40' : 'u7',
                },
                '512' : {   # entity action
                    'name' : 'entity_action',
                    '0a' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    }
                },
                '51a' : {   # physics platform
                    'name' : 'physics_platform',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '522' : {   # entity info
                    'name' : 'entity_info',
                    '0a' : 'name',
                },
                '52a' : {   # hero entity
                    'name' : 'hero_entity',
                    '0a' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    }
                },
                '642' : {   # file
                    'name' : 'file',
                    '0a' : 'filename',
                },
                '692' : {   # properties
                    'name' : 'properties',
                    '0a' : 'u0',
                },
                '7d2' : {   # particle emitter
                    'name' : 'particle_emitter',
                    '10' : 'particle',
                    '18' : 'u1',
                    '20' : 'u2',
                    '28' : 'u3',
                    '30' : 'u4',
                    '3a' : {
                        'name' : 'u5',
                        '08' : 'u0',
                        '12' : {
                            'name' : 'u1',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '1d' : 'u2',
                        '25' : 'u3',
                        '2d' : 'u4',
                        '35' : 'u5',
                        '3a' : {
                            'name' : 'u6',
                            '0d' : 'u0',
                            '15' : 'u1',
                            '1d' : 'u2',
                        }
                    },
                    '40' : 'u6',
                    '4a' : {
                        'name' : 'u7',
                        '0d' : 'u0',
                        '15' : 'u1',
                        '1d' : 'u2',
                    },
                    '52' : {
                        'name' : 'u8',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                },
                '7da' : {   # particle
                    'name' : 'particle',
                    '0a' : 'name',
                    '15' : 'u0',
                },
                '7ea' : {   # fire emitter
                    'name' : 'fire_emitter',
                    '08' : 'particle_emitter',
                    '18' : 'light',
                    '2a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '35' : 'u1',
                    '3d' : 'u2',
                    '42' : {
                        'name' : 'u3',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '4a' : {
                        'name' : 'u4',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                },
                '7f2' : {   # simple glow
                    'name' : 'simple_glow',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '15' : 'u1',
                    '18' : 'u2',
                    '25' : 'u3',
                    '2d' : 'u4',
                    '35' : 'u5',
                    '3a' : {
                        'name' : 'u6',
                        '0d' : 'y',
                        '15' : 'z',
                    },
                },
                '802' : {   # orbit controller
                    'name' : 'orbit_controller',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '15' : 'speed',
                    '1d' : 'radius',
                },
                '972' : {   # monster controller
                    'name' : 'monster_controller',
                    '0d' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '20' : 'u3',
                },
                '982' : {   # charging monster controller
                    'name' : 'charging_monster_controller',
                    '08' : 'walk_animation',
                    '10' : 'charge_animation',
                    '18' : 'run_animation',
                    '25' : 'u0',
                    '2d' : 'u1',
                },
                '98a' : {    #t
                    'name' : 'temp1',
                    '08' : 'u0',
                    '10' : 'u2',
                    '18' : 'u3',
                    '20' : 'u4',
                    '28' : 'u5',
                },
                '992' : {   # attack
                    'name' : 'attack',
                    '08' : 'keyframe_animation_component',
                    '10' : 'u0',
                    '18' : 'u1',
                    '20' : 'u2',
                    '2d' : 'u3',
                    '35' : 'u4',
                    '3d' : 'u5',
                    '45' : 'u6',
                    '4d' : 'u7',
                    '55' : 'u8',
                    '5a' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '65' : 'u9',
                    '6d' : 'u10',
                },
                '9aa' : {   # static monster controller
                    'name' : 'static_monster_controller',
                    '08' : 'u0',
                },
                '9c2' : {   # bouncing monster controller
                    'name' : 'bouncing_monster_controller',
                    '08' : 'jump_animation',
                    '10' : 'land_animation',
                    '1d' : 'u0',
                    '25' : 'u1',
                },
                '9d2' : {   # generic monster controller
                    'name' : 'generic_monster_controller',
                    '08' : 'walk_animation',
                },
                'c82' : {   # swingable weapon
                    'name' : 'swingable_weapon',
                    '08' : 'linked_model_component_number',
                    '10' : 'u1',
                    '20' : 'u2',
                    '28' : 'u3',
                    '30' : 'u4',
                    '38' : 'u5',
                    '40' : 'u6',
                    '48' : 'u7',
                    '55' : 'w',
                    '5d' : 'x',
                    '65' : 'y',
                    '6d' : 'z',
                    '72' : 'u8',
                },
                'c8a' : {   # swingable weapon controller
                    'name' : 'swingable_weapon_controller',
                    '08' : 'parent_model',
                    '12' : 'bone',
                    '1a' : 'child_model'
                },
                'c9a' : {   # weapon glow
                    'name' : 'weapon_glow',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '25' : 'u3',
                },
                'ca2' : {   # weapon trail
                    'name' : 'weapon_trail',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    }
                },
                'fa2' : {   # portal
                    'name' : 'portal',
                    '0a' : 'target_level',
                    '12' : 'spawnpoint',
                    '18' : 'touchable',
                    '20' : 'collision_shape_component',
                },
                'faa' : {   # spawnpoint
                    'name' : 'spawnpoint',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    }
                },
                'fb2' : {   # collectable item
                    'name' : 'collectable_item',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'lua_chunk',
                        '0a' : [1,'main_chunk'],
                        '12' : [2, 'secondary_chunk'],
                    },
                    '22' : 'name',
                    '2a' : '?model',
                    '30' : 'u0',
                },
                'fca' : {   # item drop
                    'name' : 'item_drop',
                    '0a' : 'name',
                    '12' : 'identifier',
                    '1a' : {   # item
                        'name' : 'item',
                        '0a' : 'item_type',
                        '12' : 'identifier',
                        '1d' : 'u0',
                        '20' : 'u1',
                        '28' : 'u2',
                    },
                    '20' : 'u0',
                    '28' : 'u1',
                },
                '1132' : {   # magic bolt
                    'name' : 'magic_bolt',
                    '08' : 'u0',
                    '10' : 'u1',
                    '18' : 'u2',
                    '22' : {
                        'name' : 'u3',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '2d' : 'u4',
                },
                '113a' : {   # magic explosion
                    'name' : 'magic_explosion',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '25' : 'u3',
                    '2d' : 'u4',
                },
                '1142' : {   # skill
                    'name' : 'skill',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'x',
                        '15' : 'y',
                        '1d' : 'z',
                    },
                    '1a' : 'cast_animation',

                },
                '114a' : {   # magic spell cast
                    'name' : 'magic_spell_cast',
                    '08' : 'particle_emitter',
                    '10' : 'u0',
                },
                '115a' : {   # projectile controller
                    'name' : 'projectile_controller',
                    '08' : 'u0',
                    '10' : 'u1',
                },
                '1172' : { #t
                    'name' : 'temp0',
                },
            },
            '22' : {
                'name' : 'u0',
                '0d' : 'y',
                '15' : 'z',
            },
            '2d' : 'u1',
            '35' : 'u2',
            '3d' : 'u3',
            '42' : {
                'name' : 'u4',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '52' : {
                'name' : 'lua_chunk',
                '0a' : [1,'main_chunk'],
                '12' : [2, 'secondary_chunk'],
            },
            '48' : 'u5',
        },
        '15' : 'u1',
    },
    '2a' : {
        'name' : 'lua_chunk',
        '0a' : [1,'main_chunk'],
        '12' : [2, 'secondary_chunk'],
        '1a' : 'name'
    },
    '1a' : 'scl_file',
},


'1a' : {
    'name' : 'u0',
    '0d' : 'w',
    '15' : 'x',
    '1d' : 'y',
    '25' : 'z',
},


'22' : {
    'name' : 'group',
    '0a' : 'name',
    '12' : 'object',
    '18' : 'u0',
    '28' : 'u1',
    '30' : 'u2',
},

'2a' : {
    'name' : 'lua_chunk',
    '0a' : [1,'main_chunk'],
    '12' : [2, 'secondary_chunk'],
},


}


bf_scl = {

'name' : 'root',

'0a' : 'scl_file_name',


'12' : {
    'name' : '?item',
    '0a' : {
        'name' : '?sub_item',
        '12' : 'name',
        '1a' : {
            'name' : 'component',
            '0a' : 'component_type',
            '10' : 'number',
            '1a' : 'name',
            '20' : '?linked_component',
            '322' : {   # sprite
                'name' : 'sprite',
            },
            '32a' : {   # model
                'name' : '3D_model',
                '0a' : 'name',
                '15' : 'u0',
                '1d' : 'u1',
                '25' : 'u2',
                '2a' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '32' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '38' : 'u5',
                '42' : {
                    'name' : 'u6',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
            },
            '332' : {   # keyframe animation
                'name' : 'keyframe_animation',
                '08' : 'linked_model_component_number',
                '12' : 'name',
                '18' : 'u0',
                '25' : 'u1',
                '28' : 'u2',
            },
            '33a' : {   # blend animation
                'name' : 'blend_animation',
                '08' : 'animation_1',
                '10' : 'animation_2',
                '1d' : 'u0',
                '25' : 'u1',
            },
            '342' : {   # model transform controller
                'name' : 'model_transform_controller',
                '08' : 'u0',
                '1a' : {
                    'name' : 'u1',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '2d' : 'u2',
            },
            '372' : {   # ground polygon
                'name' : 'ground_polygon',
                '12' : {
                    'name' : 'vertex_list',
                    '0a' : {
                        'name' : 'vertex_pos',
                        '0d' : 'x',
                        '15' : 'y',
                    },
                    '10' : 'u0',
                    '18' : 'u1',
                },
                '18' : 'u1',
                '25' : 'u2',
                '2d' : 'u3',
                '32' : 'u4',
                '3d' : 'u5',
                '40' : 'u6',
            },
            '37a' : {   # ground mesh
                'name' : 'ground_mesh',
                '3a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '42' : {
                    'name' : 'u1',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '22' : {
                        'name' : 'u3',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '2a' : {
                        'name' : 'u4',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '32' : {
                        'name' : 'u5',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '52' : {
                        'name' : 'u6',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '12' : {
                            'name' : 'u1',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '1a' : {
                            'name' : 'u2',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '25' : 'u3',
                        '2a' : 'u4',
                    },
                    '5a' : {
                        'name' : 'u7',
                        '0d' : 'u',
                        '15' : 'v',
                        '1d' : 'w',
                        '25' : 'x',
                        '2d' : 'y',
                        '35' : 'z',
                    },
                    '192' : 'u8',
                    '19a' : 'u9',
                },
                '4a' : {
                    'name' : 'u2',
                    '08' : 'u0',
                    '10' : 'u1',
                    '22' : {
                        'name' : 'u2',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '2a' : {
                        'name' : 'u3',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '32' : {
                        'name' : 'u4',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '52' : {
                        'name' : 'u5',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '12' : {
                            'name' : 'u1',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '1a' : {
                            'name' : 'u2',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '25' : 'u3',
                        '2a' : {
                            'name' : 'u4',
                            '0a' : 'u0',
                            '10' : 'u1',
                            '20' : 'u2',
                        },
                    },
                    '5a' : {
                        'name' : 'u6',
                        '0d' : 'u',
                        '15' : 'v',
                        '1d' : 'w',
                        '25' : 'x',
                        '2d' : 'y',
                        '35' : 'z',
                    },
                    '192' : 'u7',
                },
                '52' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '58' : 'u4',
            },
            '382' : {   # ground mesh generator
                'name' : 'ground_mesh_generator',
                '08' : 'ground_polygon',
                '10' : 'ground_mesh',
                '18' : 'texture_mapping_1',
                '20' : 'texture_mapping_2',
                '28' : 'u4',
                '35' : 'u5',
                '38' : 'u6',
                '45' : 'u7',
                '4d' : 'u8',
                '55' : 'u9',
                '5d' : 'u10',
                '73f2' : 'u11',
            },
            '38a' : {   # texture mapping
                'name' : 'texture_mapping',
                '0a' : 'texture_file',
                '15' : 'u0',
                '1a' : {
                    'name' : 'u1',
                    '0d' : 'u1',
                    '15' : 'u2',
                },
            },
            '392' : {   # water mesh
                'name' : 'water_mesh',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '22' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },

            },
            '3c2' : {   # collision shape
                'name' : 'collision_shape',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '12' : {
                    'name' : 'u1',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'y',
                        '15' : 'z',
                    },
                    '15' : 'u1',
                },
                '1a' : {
                    'name' : 'u2',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'y',
                        '15' : 'z',
                    },
                    '10' : 'u3',
                    '18' : 'u4',
                },
            },
            '3ca' : {   # collision shape 2
                'name' : 'collision_shape_2',
                '10' : 'u0',
                '18' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '35' : 'w',
                '3d' : 'x',
                '40' : 'interaction_type',
                '4a' : {
                    'name' : 'lua_chunk_0',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '52' : {
                    'name' : 'lua_chunk_1',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '58' : 'z',
                '62' : {
                    'name' : 'lua_chunk_2',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '6d' : 'u4',
                '70' : 'u5',
            },
            '3d2' : {   # damage
                'name' : 'damage',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '20' : 'u3',
                '28' : 'u4',
                '35' : 'u5',
                '3d' : 'u6',
                '40' : 'u7',
                '48' : 'u8',
            },
            '3da' : {   # health
                'name' : 'health',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                }
            },
            '3e2' : {   # bone controlled collision shape
                'name' : 'bone_controlled_collision_shape',
                '08' : 'u0',
                '12' : 'bone_name',
            },
            '3ea' : {   # object link controller
                'name' : 'object_link_controller',
                '0a' : 'u0',
                '12' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '22' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '2a' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },     
            '412' : {   # light
                'name' : 'light',
                '08' : 'u0',
                '15' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u3',
                '2d' : 'u4',
                '32' : {
                    'name' : 'u5',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '3d' : 'u6',
            },
            '41a' : {
                'name' : 'shadow',
                '0d' : 'u0',
                '15' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '462' : {   # sound effect
                'name' : 'sound_effect',
                '0a' : 'sound',
                '15' : 'u0',
                '1d' : 'u1',
            },
            '4aa' : {   # animation controller
                'name' : 'animation_controller',
                '08' : 'model_component',
                '10' : 'u1',
                '18' : 'u2',
            },
            '4b2' : {   # char anim controller
                'name' : 'char_anim_controller',
                '20' : 'u0',
                '28' : 'u1',
                '30' : 'u2',
                '38' : 'u3',
                '40' : 'u4',
                '48' : 'u5',
            },
            '4ba' : {   # char controller
                'name' : 'char_controller',
                '08' : 'u0',
                '10' : 'u1',
                '1d' : 'run_speed',
                '25' : 'jump_height',
                '2d' : 'u4',
                '30' : 'u5',
                '38' : 'u6',
                '40' : 'u7',
                '48' : 'u8',
                '50' : 'u9',
                '58' : 'u10',
                '60' : 'u11',
                '68' : 'u12',
                '70' : 'u13',
                '78' : 'u14',
                '85' : 'sprint_speed',
                '8d' : 'u16',
                '90' : 'u17',
                '98' : 'u18',
                'a0' : 'u19',
                
            },
            '4c2' : {   # entity
                'name' : 'entity',
                '08' : 'u0',
                '10' : 'u1',
            },
            '4ca' : {   # bush controller
                'name' : 'bush_controller',
                '08' : 'touched_animation',
                '10' : 'u0',
                '18' : 'u1',
            },
            '4d2' : {   # elevator controller
                'name' : 'elevator_controller',
                '08' : 'utility_shape_component',
                '10' : 'u0',
            },
            '4da' : {   # pressure trigger
                'name' : 'pressure_trigger',
                '0d' : 'u0',
                '12' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '1a' : 'u1',
                '20' : 'u2',
            },
            '4f2' : {   # ?monster entity
                'name' : '?monster_entity',
                '0a' : 'u0',
                '12' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '18' : 'u2',
                '20' : 'u3',
            },
            '4fa' : {   # physics object
                'name' : 'physics_object',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'u0',
                    '15' : 'u1',
                },
                '1d' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '35' : 'u5',
                '38' : 'u6',
                '45' : 'u7',
            },
            '4e2' : {   # door controller
                'name' : 'door_controller',
                '08' : 'u0',
                '10' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
            },
            '4ea' : {   # program
                'name' : 'program',
                '08' : 'u0',
                '12' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '18' : 'u1',
                '20' : 'u2',
            },
            '502' : {   # breakable object
                'name' : 'breakable_object',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '22' : 'u3',
            },
            '50a' : {   # entity controller
                'name' : 'entity_controller',
                '08' : 'entity_component',
                '10' : 'animation_controller_component',
                '18' : 'u2',
                '20' : 'collision_shape',
                '2d' : 'u4',
                '35' : 'u5',
                '3d' : 'u6',            
                '40' : 'u7',
            },
            '512' : {   # entity action
                'name' : 'entity_action',
                '0a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                }
            },
            '51a' : {   # physics platform
                'name' : 'physics_platform',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '522' : {   # entity info
                'name' : 'entity_info',
                '0a' : 'name',
            },
            '52a' : {   # hero entity
                'name' : 'hero_entity',
                '0a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : 'secondary_chunk',
                }
            },
            '642' : {   # file
                'name' : 'file',
                '0a' : 'filename',
            },
            '692' : {   # properties
                'name' : 'properties',
                '0a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                }
            },
            '7d2' : {   # particle emitter
                'name' : 'particle_emitter',
                '10' : 'particle',
                '18' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
                '3a' : {
                    'name' : 'u5',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '1d' : 'u2',
                    '25' : 'u3',
                    '2d' : 'u4',
                    '35' : 'u5',
                    '3a' : {
                        'name' : 'u6',
                        '0d' : 'u0',
                        '15' : 'u1',
                        '1d' : 'u2',
                    }
                },
                '40' : 'u6',
                '4a' : {
                    'name' : 'u7',
                    '0d' : 'u0',
                    '15' : 'u1',
                    '1d' : 'u2',
                },
                '52' : {
                    'name' : 'u8',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '7da' : {   # particle
                'name' : 'particle',
                '0a' : 'name',
                '15' : 'u0',
            },
            '7ea' : {   # fire emitter
                'name' : 'fire_emitter',
                '08' : 'particle_emitter',
                '18' : 'light',
                '2a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '35' : 'u1',
                '3d' : 'u2',
                '42' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '4a' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '7f2' : {   # simple glow
                'name' : 'simple_glow',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '15' : 'u1',
                '18' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '35' : 'u5',
                '3a' : {
                    'name' : 'u6',
                    '0d' : 'y',
                    '15' : 'z',
                },
            },
            '802' : {   # orbit controller
                'name' : 'orbit_controller',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '15' : 'speed',
                '1d' : 'radius',
            },
            '972' : {   # monster controller
                'name' : 'monster_controller',
                '0d' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '20' : 'u3',
            },
            '97a' : {   # walking monster controller
                'name' : 'walking_monster_controller',
                '08' : 'walk_animation',
            },
            '982' : {   # charging monster controller
                'name' : 'charging_monster_controller',
                '08' : 'walk_animation',
                '10' : 'charge_animation',
                '18' : 'run_animation',
                '25' : 'u0',
                '2d' : 'u1',
            },
            '98a' : {    #t
                'name' : 'temp1',
                '08' : 'u0',
                '10' : 'u2',
                '18' : 'u3',
                '20' : 'u4',
                '28' : 'u5',
            },
            '992' : {   # attack
                'name' : 'attack',
                '08' : 'keyframe_animation_component',
                '10' : 'u0',
                '18' : 'u1',
                '20' : 'u2',
                '2d' : 'u3',
                '35' : 'u4',
                '3d' : 'u5',
                '45' : 'u6',
                '4d' : 'u7',
                '55' : 'u8',
                '5a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : 'secondary_chunk',
                },
                '65' : 'u9',
                '6d' : 'u10',
            },
            '9a2' : {   # skelly monster controller
                'name' : 'skelly_monster_controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9aa' : {   # static monster controller
                'name' : 'static_monster_controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9b2' : {   # shooting monster controller
                'name' : 'shooting_monster_controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9ba' : {   # bat monster controller
                'name' : 'bat_monster_controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9c2' : {   # bouncing monster controller
                'name' : 'bouncing_monster_controller',
                '08' : 'jump_animation',
                '10' : 'land_animation',
                '1d' : 'u0',
                '25' : 'u1',
            },
            '9ca' : {   # monster death controller
                'name' : 'monster_death_controller',
                '08' : 'particle_emitter_component',
            },
            '9d2' : {   # generic monster controller
                'name' : 'generic_monster_controller',
                '08' : 'walk_animation',
            },
            'c82' : {   # swingable weapon
                'name' : 'swingable_weapon',
                '08' : 'linked_model_component_number',
                '10' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
                '38' : 'u5',
                '40' : 'u6',
                '48' : 'u7',
                '55' : 'w',
                '5d' : 'x',
                '65' : 'y',
                '6d' : 'z',
                '72' : 'u8',
            },
            'c8a' : {   # swingable weapon controller
                'name' : 'swingable_weapon_controller',
                '08' : 'parent_model',
                '12' : 'bone',
                '1a' : 'child_model'
            },
            'c92' : {   # swing
                'name' : 'swing',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '35' : 'u3',
                '3d' : 'u4',
            },
            'c9a' : {   # weapon glow
                'name' : 'weapon_glow',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u3',
            },
            'ca2' : {   # weapon trail
                'name' : 'weapon_trail',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            },
            'fa2' : {   # portal
                'name' : 'portal',
                '0a' : 'target_level',
                '12' : 'spawnpoint',
                '18' : 'touchable',
                '20' : 'collision_shape_component',
            },
            'faa' : {   # spawnpoint
                'name' : 'spawnpoint',
                '08' : 'u0',
                '12' : 'u1',
            },
            'fb2' : {   # collectable item
                'name' : 'collectable_item',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                },
                '22' : 'name',
                '2a' : '?model',
                '30' : 'u0',
            },
            'fca' : {   # item drop
                'name' : 'item_drop',
                '0a' : 'name',
                '12' : 'identifier',
                '1a' : {   # item
                    'name' : 'item',
                    '0a' : 'item_type',
                    '12' : 'identifier',
                    '1d' : 'u0',
                    '20' : 'u1',
                    '28' : 'u2',
                },
                '20' : 'u0',
                '28' : 'u1',
            },
            'fda' : {   # portal effect
                'name' : 'portal_effect',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '22' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '1132' : {   # magic bolt
                'name' : 'magic_bolt',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '22' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '2d' : 'u4',
            },
            '113a' : {   # magic explosion
                'name' : 'magic_explosion',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u3',
                '2d' : 'u4',
            },
            '1142' : {   # skill
                'name' : 'skill',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '1a' : 'cast_animation',

            },
            '114a' : {   # magic spell cast
                'name' : 'magic_spell_cast',
                '08' : 'particle_emitter',
                '10' : 'u0',
            },
            '1152' : {   # fire breath
                'name' : 'fire_breath',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            },
            '115a' : {   # projectile controller
                'name' : 'projectile_controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '1162' : {   # magic bomb
                'name' : 'magic_bomb',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            }, 
            '116a' : {   # magic hookshot
                'name' : 'magic_hookshot',
                '08' : 'particle_emitter_component',
                '10' : 'u0',
                '18' : 'u1',
                '22' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '28' : 'u3',
            },
            '1172' : { #t
                'name' : 'temp0',
                '0a' : {
                    'name' : 'lua_chunk',
                    '0a' : [1,'main_chunk'],
                    '12' : [2, 'secondary_chunk'],
                }
            },
        
        },
        '22' : {
            'name' : 'position',
            '0d' : 'x_position',
            '15' : 'y_position',
        },
        '2d' : 'z_position',
        '35' : 'rotation',
        '3d' : 'scale',
        '42' : {
            'name' : 'u0',
            '0d' : 'w',
            '15' : 'x',
            '1d' : 'y',
            '25' : 'z',
        },
        '48' : 'hidden',
        '52' : {
            'name' : 'lua_chunk',
            '0a' : [1,'main_chunk'],
            '12' : [2, 'secondary_chunk'],
        },
    },
    
    '15' : 'u0',
    
},


'1a' : '?dependancy',


'2a' : {
    'name' : 'lua_chunk',
    '0a' : [1,'main_chunk'],
    '12' : [2, 'secondary_chunk'],
    '1a' : 'program_name',
},


}


bf_gdata = {

'name' : 'root',


'0a' : {   # collectable item

    'name' : 'collectable_item',
    '12' : 'name',
    '1a' : 'title',
    '22' : 'subtitle',
    '2a' : 'info',
    # item types : 1=non-collectable,2=sword,3=armour,4=trinket,5=collectable
    '08' : 'item_type',
    '30' : 'unique_item',
    '38' : 'min_damage',
    '40' : 'max_damage',
    '48' : 'sequence_position'

},
'12' : {   # skill

    'name' : 'skill',
    '0a' : 'name',
    '12' : 'title',
    '1a' : 'subtitle',
    '20' : 'u0',
    '28' : 'min_damage',
    '30' : 'max_damage'

},
'1a' : {   # quest

    'name' : 'quest',
    '0a' : 'name',
    '12' : 'title',
    '22' : 'target_level'
    
},
'22' : {   # entity info

    'name' : 'entity_info',
    '0a' : 'name',
    '12' : 'title',
    '18' : 'u0',
    '20' : 'u1',
    '28' : 'u2',
    '30' : 'u3',
    '3d' : 'u4',
    '45' : 'u5',
    
},
'2a' : {   # compass info

    'name' : 'compass_info',
    '08' : 'u0',
    '12' : 'name',
    '1a' : 'target_level',
    '22' : 'target_object',
    '2a' : 'u1',
    '30' : 'u2',
    '3a' : {   # waypoints

        'name' : 'waypoint',
        '0a' : 'target_level',
        '12' : 'target_object',

    },
    
},


}


bf_gopt = {

'name' : 'root',

'0a' : {   # music definition
    'name' : 'music_definition',
    '0a' : 'name',
    '12' : {
        'name' : 'file',
        '0a' : 'filename',
        '15' : 'u0',
    }
},

'32' : {
    'name' : 'button_positions',
    '12' : {
        'name' : 'button',
        '0a' : 'name',
        '1a' : {
            'name' : 'position',
            '0d' : 'left',
            '15' : 'right',
            '1d' : 'bottom',            
            '25' : 'top',
        },
    },
},

'3a' : {
    'name' : 'buttons',
    '12' : {
        'name' : 'button',
        '0a' : 'name',
        '1a' : {
            'name' : 'position',
            '0d' : 'left',
            '15' : 'right',
            '1d' : 'bottom',            
            '25' : 'top',
        },
    }
}

}


bf_gplayer = {

'name' : 'root',
'0a' : 'save_name',
'10' : 'percentage',
'19' : 'u0',
'22' : {
    'name' : '?player',
    '0a' : {
        'name' : 'inventory',
        '10' : 'u0',
        '20' : 'u1',
        '28' : 'u2',
        '30' : 'u3',
        '38' : 'u4',
        '5a' : {
            'name' : 'item',
            '0a' : 'name',
            '10' : 'u0',
            },
        '7a' : 'spell',
        '82' : 'selected_spell',
        '8a' : 'sword_trinket',
        '92' : 'armour_trinket',
        '9a' : 'magic_trinket',
        'a0' : 'u5',
        'a8' : 'u6',
        'b0' : 'u7',
        },
    '12' : {
        'name' : 'scene_info',
        '0a' : 'scene',
        '10' : 'u0',
        '1a' : {
            'name' : 'flags',
            '0a' : 'name',
            },
        '20' : 'u8',
        '28' : 'u9',
        },
    '1a' : 'u0',
    '22' : 'u1',
    '2a' : 'u2',
    '3a' : {
        'name' : 'u3',
        '0a' : 'u0',
        '10' : 'u1',
        },
    '42' : {
        'name' : 'flags',
        '0a' : 'flag',
        },
    '4a' : 'last_menu_screen',
    '52' : 'u4',
    '5a' : 'u5',
    '62' : {
        'name' : 'quest_text',
        '0a' : 'name',
        '12' : 'text',
        },
    '6a' : 'u6',
    '70' : 'u7',
    '78' : 'u8',
    '82' : 'u9',
    '8a' : 'u10',
    '90' : 'u11',
    '98' : 'u12',
    'a0' : 'u13',
    'a8' : 'u14',
    },
'2a' : 'u0',
'32' : 'u1',
'3a' : 'u2',
'42' : 'u3',
'4a' : 'u4',
'52' : {
    'name' : 'u5',
    '09' : 'u0',
    },
'5d' : 'u6',
'62' : {
        'name' : 'achievement_counter',
        '0a' : 'name',
        '10' : 'count',
    },
'72' : 'player_id',
    
}


bf_gstate = {

'name' : 'root',

'0a' : {
    'name' : 'inventory',
    '28' : 'soul_shards',
    '5a' : {
        'name' : 'item',
        '0a' : 'name',
    },
    '7a' : 'skill',
    '82' : 'selected_skill',
    '8a' : 'sword_trinket',
},
'1a' : 'spawn_level',
'22' : 'spawnpoint',
'4a' : 'u1',

}


bf_scmap = {

'name' : 'root',

'12' : {   # zone

'name' : 'zone',
'0a' : 'name',
'12' : 'title',
'1a' : {   # scene

    'name' : 'scene',
    '12' : 'name',
    '1a' : {   # connected scene
    
        'name' : 'connected_scene',
        '0a' : 'name',
        # directions: 1=right 2=top-right 3=top 3=top-left etc.
        '10' : 'direction',
        '18' : 'u1',
        '20' : 'base_enemy_level'
        },

    # features: 1=town 2=??? 3=boss
    '20' : 'feature',
    '28' : 'u1',
    '30' : 'u2',
    '3a' : 'music',
    '40' : 'u3',
    '48' : 'treasures',
    '52' : 'title',
    '58' : 'u5',
    },

'20' : 'sequence',
'2a' : 'default_music',
}
}


bf_sounds = {

'name' : 'root',

'0a' : {
    'name' : 'sound',
    '0a' : 'name',
    '12' : 'file',
    '1d' : 'u0',
    '25' : 'u1',
}

}
